// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identities.proto

package msp

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// This struct represents an Identity
// (with its MSP identifier) to be used
// to serialize it and deserialize it
type SerializedIdentity struct {
	// The identifier of the associated membership service provider
	Mspid string `protobuf:"bytes,1,opt,name=mspid,proto3" json:"mspid,omitempty"`
	// the Identity, serialized according to the rules of its MPS
	IdBytes              []byte   `protobuf:"bytes,2,opt,name=id_bytes,json=idBytes,proto3" json:"id_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedIdentity) Reset()         { *m = SerializedIdentity{} }
func (m *SerializedIdentity) String() string { return proto.CompactTextString(m) }
func (*SerializedIdentity) ProtoMessage()    {}
func (*SerializedIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb899f6f31212f0, []int{0}
}

func (m *SerializedIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedIdentity.Unmarshal(m, b)
}
func (m *SerializedIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedIdentity.Marshal(b, m, deterministic)
}
func (m *SerializedIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedIdentity.Merge(m, src)
}
func (m *SerializedIdentity) XXX_Size() int {
	return xxx_messageInfo_SerializedIdentity.Size(m)
}
func (m *SerializedIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedIdentity proto.InternalMessageInfo

func (m *SerializedIdentity) GetMspid() string {
	if m != nil {
		return m.Mspid
	}
	return ""
}

func (m *SerializedIdentity) GetIdBytes() []byte {
	if m != nil {
		return m.IdBytes
	}
	return nil
}

// This struct represents an Idemix Identity
// to be used to serialize it and deserialize it.
// The IdemixMSP will first serialize an idemix identity to bytes using
// this proto, and then uses these bytes as id_bytes in SerializedIdentity
type SerializedIdemixIdentity struct {
	// nym_x is the X-component of the pseudonym elliptic curve point.
	// It is a []byte representation of an amcl.BIG
	// The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
	NymX []byte `protobuf:"bytes,1,opt,name=nym_x,json=nymX,proto3" json:"nym_x,omitempty"`
	// nym_y is the Y-component of the pseudonym elliptic curve point.
	// It is a []byte representation of an amcl.BIG
	// The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
	NymY []byte `protobuf:"bytes,2,opt,name=nym_y,json=nymY,proto3" json:"nym_y,omitempty"`
	// ou contains the organizational unit of the idemix identity
	Ou []byte `protobuf:"bytes,3,opt,name=ou,proto3" json:"ou,omitempty"`
	// role contains the role of this identity (e.g., ADMIN or MEMBER)
	Role []byte `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// proof contains the cryptographic evidence that this identity is valid
	Proof                []byte   `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedIdemixIdentity) Reset()         { *m = SerializedIdemixIdentity{} }
func (m *SerializedIdemixIdentity) String() string { return proto.CompactTextString(m) }
func (*SerializedIdemixIdentity) ProtoMessage()    {}
func (*SerializedIdemixIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb899f6f31212f0, []int{1}
}

func (m *SerializedIdemixIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedIdemixIdentity.Unmarshal(m, b)
}
func (m *SerializedIdemixIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedIdemixIdentity.Marshal(b, m, deterministic)
}
func (m *SerializedIdemixIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedIdemixIdentity.Merge(m, src)
}
func (m *SerializedIdemixIdentity) XXX_Size() int {
	return xxx_messageInfo_SerializedIdemixIdentity.Size(m)
}
func (m *SerializedIdemixIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedIdemixIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedIdemixIdentity proto.InternalMessageInfo

func (m *SerializedIdemixIdentity) GetNymX() []byte {
	if m != nil {
		return m.NymX
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetNymY() []byte {
	if m != nil {
		return m.NymY
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetOu() []byte {
	if m != nil {
		return m.Ou
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetRole() []byte {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *SerializedIdemixIdentity) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

// This struct represents an IBPCLA Identity
// to be used to serialize it and deserialize it.
// The IBPCLAMSP will first serialize an ibpcla identity to bytes using
// this proto, and then uses these bytes as id_bytes in SerializedIdentity
type SerializedIBPCLAIdentity struct {
	// PA is the vice identity, it is an elliptic curve point generated from KGC.
	// It is a []byte representation of BIG.int with X coordinate along with Y coordinate
	// PA is used to recover public keys then verify signatures.
	PA []byte `protobuf:"bytes,1,opt,name=PA,proto3" json:"PA,omitempty"`
	// ou contains the organizational unit of the ibpcla identity
	Ou []byte `protobuf:"bytes,2,opt,name=ou,proto3" json:"ou,omitempty"`
	// role contains the role of this identity (e.g., ADMIN or MEMBER)
	Role                 []byte   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedIBPCLAIdentity) Reset()         { *m = SerializedIBPCLAIdentity{} }
func (m *SerializedIBPCLAIdentity) String() string { return proto.CompactTextString(m) }
func (*SerializedIBPCLAIdentity) ProtoMessage()    {}
func (*SerializedIBPCLAIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb899f6f31212f0, []int{2}
}

func (m *SerializedIBPCLAIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedIBPCLAIdentity.Unmarshal(m, b)
}
func (m *SerializedIBPCLAIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedIBPCLAIdentity.Marshal(b, m, deterministic)
}
func (m *SerializedIBPCLAIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedIBPCLAIdentity.Merge(m, src)
}
func (m *SerializedIBPCLAIdentity) XXX_Size() int {
	return xxx_messageInfo_SerializedIBPCLAIdentity.Size(m)
}
func (m *SerializedIBPCLAIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedIBPCLAIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedIBPCLAIdentity proto.InternalMessageInfo

func (m *SerializedIBPCLAIdentity) GetPA() []byte {
	if m != nil {
		return m.PA
	}
	return nil
}

func (m *SerializedIBPCLAIdentity) GetOu() []byte {
	if m != nil {
		return m.Ou
	}
	return nil
}

func (m *SerializedIBPCLAIdentity) GetRole() []byte {
	if m != nil {
		return m.Role
	}
	return nil
}

func init() {
	proto.RegisterType((*SerializedIdentity)(nil), "msp.SerializedIdentity")
	proto.RegisterType((*SerializedIdemixIdentity)(nil), "msp.SerializedIdemixIdentity")
	proto.RegisterType((*SerializedIBPCLAIdentity)(nil), "msp.SerializedIBPCLAIdentity")
}

func init() { proto.RegisterFile("identities.proto", fileDescriptor_0bb899f6f31212f0) }

var fileDescriptor_0bb899f6f31212f0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xf3, 0x30,
	0x1c, 0xc6, 0x69, 0xda, 0xbe, 0xaf, 0x86, 0x31, 0x24, 0x7a, 0x88, 0xb7, 0xd9, 0x53, 0x4f, 0xed,
	0xc1, 0x4f, 0xd0, 0x8a, 0x07, 0x41, 0xa5, 0xd4, 0x8b, 0x7a, 0x19, 0xeb, 0x92, 0x75, 0x7f, 0x68,
	0x9a, 0x90, 0xa4, 0xb0, 0x78, 0xf0, 0xb3, 0x4b, 0x9b, 0x3a, 0x1d, 0xde, 0xfe, 0xcf, 0xc3, 0x8f,
	0xe7, 0x17, 0x82, 0x2f, 0x80, 0xf1, 0xde, 0x82, 0x05, 0x6e, 0x32, 0xa5, 0xa5, 0x95, 0x24, 0x14,
	0x46, 0x25, 0xf7, 0x98, 0xbc, 0x70, 0x0d, 0x9b, 0x0e, 0x3e, 0x38, 0x7b, 0xf0, 0x88, 0x23, 0x57,
	0x38, 0x16, 0x46, 0x01, 0xa3, 0xc1, 0x2a, 0x48, 0xcf, 0x6b, 0x1f, 0xc8, 0x35, 0x3e, 0x03, 0xb6,
	0x6e, 0x9c, 0xe5, 0x86, 0xa2, 0x55, 0x90, 0x2e, 0xea, 0xff, 0xc0, 0xca, 0x31, 0x26, 0x9f, 0x98,
	0x9e, 0xcc, 0x08, 0x38, 0x1c, 0xc7, 0x2e, 0x71, 0xdc, 0x3b, 0xb1, 0x3e, 0x4c, 0x63, 0x8b, 0x3a,
	0xea, 0x9d, 0x78, 0xfd, 0x2e, 0xdd, 0x3c, 0x34, 0x96, 0x6f, 0x64, 0x89, 0x91, 0x1c, 0x68, 0x38,
	0x35, 0x48, 0x0e, 0x84, 0xe0, 0x48, 0xcb, 0x8e, 0xd3, 0xc8, 0x33, 0xe3, 0x3d, 0x3e, 0x4d, 0x69,
	0x29, 0x77, 0x34, 0x9e, 0x4a, 0x1f, 0x92, 0xe7, 0x13, 0x7f, 0x59, 0xdd, 0x3d, 0x16, 0x47, 0xff,
	0x12, 0xa3, 0xaa, 0x98, 0xe5, 0xa8, 0x2a, 0x66, 0x0b, 0xfa, 0x63, 0x09, 0x7f, 0x2c, 0xe5, 0x13,
	0xbe, 0x91, 0xba, 0xcd, 0xf6, 0x4e, 0x71, 0xdd, 0x71, 0xd6, 0x72, 0x9d, 0xed, 0x36, 0x8d, 0x86,
	0xad, 0xff, 0x3b, 0x93, 0x09, 0xa3, 0xde, 0xd3, 0x16, 0xec, 0x7e, 0x68, 0xb2, 0xad, 0x14, 0xf9,
	0x2f, 0x32, 0xf7, 0x64, 0xee, 0xc9, 0x5c, 0x18, 0xd5, 0xfc, 0x9b, 0xee, 0xdb, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x34, 0x12, 0xb9, 0x85, 0x01, 0x00, 0x00,
}
