ID: peer0.org1.example.com
NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: kgcpubs/kgc.org1.example.com-pubkey.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: kgcpubs/kgc.org1.example.com-pubkey.pem
    OrganizationalUnitIdentifier: peer
