// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ibpcla.proto

package ibpcla

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PartialKeyRequest specifies a partial key request object that consists of
// XA - generated from client
// algo - algorithm (p256 or SM)
type PartialKeyRequest struct {
	XA                   []byte   `protobuf:"bytes,1,opt,name=XA,proto3" json:"XA,omitempty"`
	Algo                 string   `protobuf:"bytes,2,opt,name=algo,proto3" json:"algo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartialKeyRequest) Reset()         { *m = PartialKeyRequest{} }
func (m *PartialKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PartialKeyRequest) ProtoMessage()    {}
func (*PartialKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8017e9a8f60785f3, []int{0}
}

func (m *PartialKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartialKeyRequest.Unmarshal(m, b)
}
func (m *PartialKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartialKeyRequest.Marshal(b, m, deterministic)
}
func (m *PartialKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartialKeyRequest.Merge(m, src)
}
func (m *PartialKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PartialKeyRequest.Size(m)
}
func (m *PartialKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartialKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartialKeyRequest proto.InternalMessageInfo

func (m *PartialKeyRequest) GetXA() []byte {
	if m != nil {
		return m.XA
	}
	return nil
}

func (m *PartialKeyRequest) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func init() {
	proto.RegisterType((*PartialKeyRequest)(nil), "PartialKeyRequest")
}

func init() { proto.RegisterFile("ibpcla.proto", fileDescriptor_8017e9a8f60785f3) }

var fileDescriptor_8017e9a8f60785f3 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4c, 0x2a, 0x48,
	0xce, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe7, 0x12, 0x0c, 0x48, 0x2c, 0x2a,
	0xc9, 0x4c, 0xcc, 0xf1, 0x4e, 0xad, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3,
	0x62, 0x8a, 0x70, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x62, 0x8a, 0x70, 0x14, 0x12, 0xe2,
	0x62, 0x49, 0xcc, 0x49, 0xcf, 0x97, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x9d, 0xd4,
	0xa2, 0x54, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x33, 0x2a, 0x0b,
	0x52, 0x8b, 0x72, 0x52, 0x53, 0xd2, 0x53, 0x8b, 0xf4, 0xd3, 0x12, 0x93, 0x8a, 0x32, 0x93, 0xf5,
	0x21, 0xd6, 0x24, 0xb1, 0x81, 0xed, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xd2, 0xb8,
	0x28, 0x77, 0x00, 0x00, 0x00,
}
